Projeto/Projeto/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf.urls import handler404, handler500
from agenda import views as agenda_views
urlpatterns = [
# Inclui as URLs do app agenda
    path('', include('agenda.urls', namespace='agenda')),


    path('account/',include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

handler404 = agenda_views.error_404
handler500 = agenda_views.error_500

Projeto/agenda/urls.py
from agenda.views import IndexTemplateView, ContatoListView, ContatoUpdateView, ContatoCreateView, \
    ContatoDeleteView

from django.urls import path

app_name = 'agenda'

urlpatterns = [
    # GET /
    path('', IndexTemplateView.as_view(), name="index"),

    # GET /contato/cadastrar
    path('contato/cadastrar', ContatoCreateView.as_view(), name="cadastra_contato"),

    # GET /contato
    path('contatos/', ContatoListView.as_view(), name="lista_contatos"),

    # GET/POST /contato/{pk}
    path('contato/<pk>', ContatoUpdateView.as_view(), name="atualiza_contato"),

    # GET/POST /contatos/excluir/{pk}
    path('contato/excluir/<pk>', ContatoDeleteView.as_view(), name="deleta_contato"),
]

Projeto/Projeto/models.py
from django.db import models

# Create your models here.


class Contato(models.Model):

    nome = models.CharField(
        max_length=255,
        null=False,
        blank=False
    )

    sobrenome = models.CharField(
        max_length=255,
        null=False,
        blank=False
    )

    email = models.CharField(
        max_length=255,
        null=False,
        blank=False
    )

    telefone = models.CharField(
        max_length=9,
        null=False,
        blank=False
    )


objetos = models.Manager()

def __str__(self):
    return self.nome + ''

Projeto/agenda/forms.py
from Projeto.models import Contato
from django import forms


# FORMULÁRIO DE INCLUSÃO DE CONTATOS
# -------------------------------------------

class InsereContatoForm(forms.ModelForm):

    # chefe = forms.BooleanField(
    #     label='Chefe?',
    #     required=False,
    # )

    # biografia = forms.CharField(
    #     label='Biografia',
    #     required=False,
    #     widget=forms.Textarea
    # )

    class Meta:
        # Modelo base
        model = Contato

        # Campos que estarão no form
        fields = [
            'nome',
            'sobrenome',
            'email',
            'telefone'
        ]

Projeto/agenda/views.py
from django.urls import reverse_lazy
from django.views.generic import TemplateView, ListView, UpdateView, CreateView, DeleteView
from Projeto.models import Contato
from agenda.forms import InsereContatoForm
from django.shortcuts import render

# PÁGINA PRINCIPAL
# ----------------------------------------------

class IndexTemplateView(TemplateView):
    template_name = "agenda/index.html"


# LISTA DE FUNCIONÁRIOS
# ----------------------------------------------

class ContatoListView(ListView):
    template_name = "agenda/lista.html"
    model = Contato
    context_object_name = "contatos"


# CADASTRAMENTO DE FUNCIONÁRIOS
# ----------------------------------------------

class ContatoCreateView(CreateView):
    template_name = "agenda/cria.html"
    model = Contato
    form_class = InsereContatoForm
    success_url = reverse_lazy("agenda:lista_contatos")


# ATUALIZAÇÃO DE FUNCIONÁRIOS
# ----------------------------------------------

class ContatoUpdateView(UpdateView):
    template_name = "agenda/atualiza.html"
    model = Contato
    fields = '__all__'
    context_object_name = 'contato'
    success_url = reverse_lazy("agenda:lista_contatos")


# EXCLUSÃO DE FUNCIONÁRIOS
# ----------------------------------------------

class ContatoDeleteView(DeleteView):
    template_name = "agenda/exclui.html"
    model = Contato
    context_object_name = 'contatos'
    success_url = reverse_lazy("agenda:lista_contatos")




def error_404(request):
        data = {}
        return render(request,'agenda/error_404.html', data)

def error_500(request):
        data = {}
        return render(request,'agenda/error_500.html', data)

Projeto/agenda/templates/agenda/_layouts/base.html
<!DOCTYPE html>
<html>
    {% load static tempo_atual %}

    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">

        <!-- Title -->
        <title>{% block title %}Sistema de Gerenciamento de Contatos{% endblock %}</title>

        <!-- Favicon -->
        <link rel="shortcut icon" href="{% static 'agenda/img/calendar.png' %}" type="image/png">

        <!-- Arquivos CSS -->
        <link rel="stylesheet" type="text/css" href="{% static 'agenda/css/bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'agenda/css/master.css' %}">

        {% block styles %}{% endblock %}
    </head>

    <body>
        <!-- Navbar -->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="{% url 'agenda:index' %}">
              <img src="{% static 'agenda/img/calendar.png' %}" height="45px">
            </a>
            <button class="navbar-toggler" type="button" 
                data-toggle="collapse" data-target="#navbarSupportedContent" 
                aria-controls="navbarSupportedContent" aria-expanded="false" 
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'agenda:index' %}">Página Inicial</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'agenda:lista_contatos' %}">Contatos</a>
                    </li>
                    {% if user.is_authenticated %}
    <li class="nav-item">
        <a class="nav-link" href="{% url 'logout' %}">Sair</a>
    </li>
{% else %}
    <li class="nav-item">
        <a class="nav-link" href="{% url 'login' %}">Login</a>
    </li>
{% endif %}
                </ul>
                <ul class="navbar-nav float-right">
                    <li class="nav-item">
                        <a class="nav-link" href="#"><b>{% if user.is_authenticated %}
    <p class="logged-in-p">
        Olá {{ user.username }} seja bem vindo!
    </p>
{% endif %}</a>
                    </li>
                </ul>
            </div>
	    </ul>
	  </div>
	</nav>
        </nav>
        
        <!-- Conteúdo do site -->
        {% block conteudo %}{% endblock %}

        <!-- Scripts .js -->
        <script src="{% static 'agenda/js/jquery.min.js' %}"></script>
        <script src="{% static 'agenda/js/bootstrap.min.js' %}"></script>

        {% block scripts %}{% endblock %}

        <script src="{% static 'agenda/js/scripts.js' %}"></script>
    </body>
</html>

Projeto/agenda/templates/agenda/atualiza.html
{% extends "agenda/_layouts/base.html" %}

{% load widget_tweaks %}

{% block title %}Atualização de Contato{% endblock %}

{% block conteudo %}
<div class="container mt-5">
  <div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Atualizar Dados de Contato</h5>
          <form method="post">
            <!-- Não se esqueça dessa tag -->
            {% csrf_token %}

            <!-- Nome -->
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text">Nome</span>
              </div>
              {% render_field form.nome class+="form-control" %}
            </div>

            <!-- Sobrenome -->
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text">Sobrenome</span>
              </div>
              {% render_field form.sobrenome class+="form-control" %}
            </div>

            <!-- EMAIL -->
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text">EMAIL</span>
              </div>
              {% render_field form.email class+="form-control" %}
            </div>

            <!-- TELEFONE -->
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text">Telefone</span>
              </div>
              {% render_field form.telefone class+="form-control" %}
            </div>

            <hr />
            <div class="text-right">
              <a href="{% url 'agenda:lista_contatos' %}" class="btn btn-outline-primary">Voltar</a>
              <button class="btn btn-primary">Enviar</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

Projeto/agenda/templates/agenda/cria.html
{% extends "agenda/_layouts/base.html" %}

{% load widget_tweaks %}

{% block title %}Cadastro de Contato{% endblock %}

{% block conteudo %}
<div class="container mt-5">
  <div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Cadastro de Funcionário</h5>
          <p class="card-text">
            Complete o formulário abaixo para cadastrar
            um novo <code>Contato</code>.
          </p>
          <form method="post">
            <!-- Não se esqueça dessa tag -->
            {% csrf_token %}

            <!-- Nome -->
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text">Nome</span>
              </div>
              {% render_field form.nome class+="form-control" %}
            </div>

            <!-- Sobrenome -->
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text">Sobrenome</span>
              </div>
              {% render_field form.sobrenome class+="form-control" %}
            </div>

            <!-- EMAIL -->
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text">EMAIL</span>
              </div>
              {% render_field form.email class+="form-control" %}
            </div>

            <!-- TELEFONE -->
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text">Telefone</span>
              </div>
              {% render_field form.telefone class+="form-control" %}
            </div>
            <hr>
            <div class="text-right">
              <a href="{% url 'agenda:lista_contatos' %}" class="btn btn-outline-primary">Voltar</a>
              <button class="btn btn-primary">Enviar</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

Projeto/agenda/templates/agenda/error_404.html
<h2>Página não encontrada</h2>
    
    <p>O endereço <i class="false">{{ request_path }}</i> é inválido ou a página que você procura não existe mais.</p>
    
    <p>Você pode ir para a <a href="/">página inicial</a> e tentar um outro endereço.</p>

Projeto/agenda/templates/agenda/error_500.html
<h1>O servidor está com erro.</h1>

Projeto/agenda/templates/agenda/exclui.html
<!-- Estendemos do template base -->
{% extends "agenda/_layouts/base.html" %}

<!-- Bloco que define o <title></title> da nossa página -->
{% block title %}Página Inicial{% endblock %}

<!-- Bloco de conteúdo da nossa página -->
{% block conteudo %}
  <div class="container mt-5">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Exclusão de Contato</h5>

        <p class="card-text">
          Você tem certeza que quer excluir o contato <b>{{ contato.nome }}</b>?
        </p>

        <form method="post">
          {% csrf_token %}

          <hr />
          <div class="text-right">
            <a href="{% url 'agenda:lista_contatos' %}" class="btn btn-outline-danger">
              Cancelar
            </a>
            <button class="btn btn-danger">Excluir</button>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

Projeto/agenda/templates/agenda/index.html
<!-- Estendemos do template base -->
{% extends "agenda/_layouts/base.html" %}

<!-- Bloco que define o <title></title> da nossa página -->
{% block title %}Página Inicial{% endblock %}

<!-- Bloco de conteúdo da nossa página -->
{% block conteudo %}
{% if user.is_authenticated %}
<div class="container mt-5">
  <div class="row">
    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Cadastrar Contato</h5>
          <p class="card-text">
            Cadastre aqui um novo <code>Contato</code>.
          </p>
          <a href="{% url 'agenda:cadastra_contato' %}"
             class="btn btn-primary">
            Novo Contato
          </a>
        </div>
      </div>
    </div>
    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Lista de Contato</h5>
          <p class="card-text">
            Veja aqui a lista de <code>Contatos</code> cadastrados.
          </p>
          <a href="{% url 'agenda:lista_contatos' %}"
             class="btn btn-primary">
            Vá para Lista
          </a>
        </div>
      </div>
    </div>
  </div>
</div>
{% else %}
<div class="container">
<p class="bem-vindo">Seja bem vindo a sua agenda de contatos, faça o login para ter acesso completo ao sistema:</p>
<button type="button" class="btn btn-primary botao-entrar" href="{% url 'login' %}" ><a class="entrar" href="{% url 'login' %}"> Entrar</a></button>
</div>
{% endif %}
{% endblock %}

Projeto/agenda/templates/agenda/lista.html
{% extends "agenda/_layouts/base.html" %}

{% block title %}Lista de Contatos{% endblock %}

{% load primeira_letra %}

{% block conteudo %}

{% if user.is_authenticated %}
<div class="container mt-5">
  <div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Lista de Contato</h5>

          {% if contatos|length > 0 %}
            <p class="card-text">
              Aqui está a lista de <code>Contatos</code> cadastrados.
            </p>

            <table class="table">
              <thead class="thead-dark">
              <tr>
                <th scope="col"></th>
                <th scope="col">Nome</th>
                <th scope="col">Sobrenome</th>
                <th scope="col">Email</th>
                <th scope="col">telefone</th>
                <th scope="col" class="text-center">Ações</th>
              </tr>
              </thead>
              <tbody>
              {% for contato in contatos %}
                <tr>
                  <th scope="row">{{ contato.nome|primeira_letra }}</th>
                  <td>{{ contato.nome }}</td>
                  <td>{{ contato.sobrenome }}</td>
                  <td>{{ contato.email }}</td>
                  <td>{{ contato.telefone }}</td>
                  <td class="text-center">
                    <a href="{% url 'agenda:atualiza_contato' pk=contato.id %}"
                       class="btn btn-primary">
                      Atualizar
                    </a>
                    <a href="{% url 'agenda:deleta_contato' pk=contato.id %}"
                      class="btn btn-danger">
                        Excluir
                    </a>
                  </td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
        {% else %}
          <div class="text-center mt-5 mb-5 jumbotron">
            <h5>Nenhum <code>Contato</code> cadastrado ainda.</h5>
          </div>
        {% endif %}
          <hr />
          <div class="text-right">
            <a href="{% url 'agenda:cadastra_contato' %}" class="btn btn-primary">
              Cadastrar Contato
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% else %}
<a href="{% url 'login' %}"> Entrar</a>
{% endif %}
{% endblock %}